tesdt

diff --git a/.github/workflows/build-binary-artifacts.yml b/.github/workflows/build-binary-artifacts.yml
--- a/.github/workflows/build-binary-artifacts.yml
+++ b/.github/workflows/build-binary-artifacts.yml
@@ -1,9 +1,12 @@
 name: Build and Sign Binary Artifacts
 on:
+  release:
+    types: [published]
   workflow_dispatch:
   push:
     branches:
       - main
+      - build-workflow-pr
     paths:
       - "lib/**"
       - "index.js"
@@ -23,10 +26,12 @@ jobs:
 
       - name: Import GPG Key
         id: import_gpg
-        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
-        with:
-          gpg_private_key: ${{ secrets.WATCHER_PRIVATE_KEY }}
-
+        run: | 
+          if ! echo "${{ secrets.WATCHER_PRIVATE_KEY }}" | gpg--import; then
+            echo "::warning ::Private key GPG Import failed"
+            exit 1
+          fi
+      
       - name: run build script
         id: run_build_script
         run: ./build.sh
@@ -70,6 +75,7 @@ jobs:
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v3
+        if: always() 
         with:
           name: binary-artifacts
           path: |
