test

diff --git a/.github/workflows/build-binary-artifacts.yml b/.github/workflows/build-binary-artifacts.yml
--- a/.github/workflows/build-binary-artifacts.yml
+++ b/.github/workflows/build-binary-artifacts.yml
@@ -24,13 +24,13 @@ jobs:
           ref: build-workflow-pr
           fetch-depth: 0
 
-      - name: Import GPG Key
-        id: import_gpg
-        run: | 
-          if ! echo "${{ secrets.WATCHER_PRIVATE_KEY }}" | gpg --import; then
-            echo "::warning ::Private key GPG Import failed"
-            exit 1
-          fi
+      # - name: Import GPG Key
+      #   id: import_gpg
+      #   run: | 
+      #     if ! echo "${{ secrets.WATCHER_PRIVATE_KEY }}" | gpg --import; then
+      #       echo "::warning ::Private key GPG Import failed"
+      #       exit 1
+      #     fi
       
       - name: run build script
         id: run_build_script
